spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
  jackson:
    default-property-inclusion: non_null